Import('env')

env_mem = env.Clone(
    CXXFLAGS= ['/std:c11', '/W2', '/Zc:wchar_t', '/Gm-'], 
    CPPDEFINES = ['MEM_EXPORTS', 'WIN32', 'DEBUGMEM_WIN32', '_WINDLL', '_MBCS', '_CRT_SECURE_NO_WARNINGS'])

objs = []
objs.append([
    'internal/error.c',
    'internal/testAndSet.c',
    'internal/Vector.c',
    'raw.c',
    'Group.c',
])

name_lib = 'memd'
if int(ARGUMENTS.get('debug', 0)):
    name_lib = 'mem' # Release version name

src = env_mem.SharedLibrary(name_lib, objs)

env_mem.Install('#lib', source=src)

env.SConscript('test/SConscript')
