Import('env')

platform = ARGUMENTS.get('OS', Platform())

#include = ['#/include', '#/src']
include = ['#/include', '#/src', '#/src/config/msvc6', 'internal']
#libs = ['user32.lib', 'gdi32.lib']

env.Append(CPPPATH=include)
#env.Append(LIBS=libs)

#objs = []
#for subdir in ['lang']:
#    o = env.SConscript('%s/SConscript' % subdir)
#    objs.append(o)

# Build SharedLibrary and StaticLibrary
for subdir in ['mem', 'lang', 'util', 'win', 'io', 'math']:
    env.SConscript('%s/SConscript' % subdir)

#o = env.Object(['main.cpp'])
#objs.append(o)

#deadjustice = env.Program('deadjustice', objs)

#Default(deadjustice)