Import('env')

#include = ['#/include', '#/src', '#/src/config/msvc6', 'internal']

#env.Append(CPPPATH=include)
env.Append(CPPDEFINES = ['LANG_WIN32', 'WIN32']) 

objs = []

# Numeric classes
objs.append([
    'Long.cpp',
    'Short.cpp',
    'Integer.cpp',    
    'Float.cpp',
    'Double.cpp',
    'Math.cpp',
])

# Char classes
objs.append([
    'Character.cpp',
    'String.cpp',
    'Formattable.cpp',
    'Format.cpp',
    'Debug.cpp',    
    'UTFConverter.cpp',
    'NumberReader.cpp',
])

# System classes
objs.append([    
    'internal/Semaphore.cpp',
    'internal/Thread_impl.cpp',
    'internal/Mutex.cpp',
    'Object.cpp',
    'System.cpp',
    'Thread.cpp',
    'DynamicLinkLibrary.cpp',
    'Throwable.cpp',
])

name_lib = 'langd'
if int(ARGUMENTS.get('debug', 0)):
    name_lib = 'lang' # Release version name

src = env.StaticLibrary(name_lib, objs)

env.Install('#lib', source=src)

env.SConscript('tests/SConscript')

#obj = env.Object(objs)
#Return('obj')